title: Volodymyr (Vlad) Tkachuk 
description: My personal website 

# Build settings
theme: minima

# Minima specific settings
minima:
  date_format: "%b %-d, %Y"

# Plugins
plugins:
 - jekyll-feed
 - jekyll-seo-tag

header_pages:
  - research.md
  - teaching.md
  - life.md